FROM python:3.13-alpine
WORKDIR /usr/src/app

# Build argument
ARG ALGORITHM

COPY sample_algorithms/Sorting/python/${ALGORITHM} ./algorithm.py
COPY tracers/ ./tracers/

CMD [ "python", "algorithm.py" ]
