"""create file table

Revision ID: 2468f9bd2233
Revises: 7fbe72577f5e
Create Date: 2026-01-28 16:46:22.699185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2468f9bd2233'
down_revision = '7fbe72577f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('folder_id', sa.Integer(), nullable=True),
        sa.Column('path', sa.String(length=1024), nullable=False),
        sa.Column('file_type', sa.Enum('user-defined', 'sample', name='object_type'), nullable=False),
        sa.Column('user_account_id', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('lang_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_updated', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['folder_id'], ['folder.folder_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['lang_id'], ['language.lang_id'], ),
        sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
        sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
