"""initial migration

Revision ID: 4af9f699614a
Revises: 
Create Date: 2026-01-28 16:37:06.065162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af9f699614a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('user_account')
    op.drop_table('reset_tokens')
    op.drop_table('folder')
    op.drop_table('closure_table')
    op.drop_table('language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('lang_id', sa.INTEGER(), nullable=False),
    sa.Column('language', sa.VARCHAR(length=50), nullable=False),
    sa.Column('docker_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('run_cmd', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('lang_id')
    )
    op.create_table('closure_table',
    sa.Column('ancestor', sa.INTEGER(), nullable=False),
    sa.Column('descendant', sa.INTEGER(), nullable=False),
    sa.Column('depth', sa.INTEGER(), nullable=False),
    sa.Column('user_account_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ancestor'], ['folder.folder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant'], ['folder.folder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ancestor', 'descendant')
    )
    op.create_table('folder',
    sa.Column('folder_id', sa.INTEGER(), nullable=False),
    sa.Column('folder_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('path', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('folder_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_folder_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folder.folder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_table('reset_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('oauth_provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('oauth_id', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('file',
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('folder_id', sa.INTEGER(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('user_account_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('lang_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.folder_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lang_id'], ['language.lang_id'], ),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###
